// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: FileExchange.proto

#include "FileExchange.pb.h"
#include "FileExchange.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace FileExchange {

static const char* SimpleFileServer_method_names[] = {
  "/FileExchange.SimpleFileServer/Upload",
  "/FileExchange.SimpleFileServer/Download",
};

std::unique_ptr< SimpleFileServer::Stub> SimpleFileServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SimpleFileServer::Stub> stub(new SimpleFileServer::Stub(channel));
  return stub;
}

SimpleFileServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Upload_(SimpleFileServer_method_names[0], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_Download_(SimpleFileServer_method_names[1], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientWriter< ::FileExchange::UploadRequest>* SimpleFileServer::Stub::UploadRaw(::grpc::ClientContext* context, ::FileExchange::UploadResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::FileExchange::UploadRequest>::Create(channel_.get(), rpcmethod_Upload_, context, response);
}

void SimpleFileServer::Stub::experimental_async::Upload(::grpc::ClientContext* context, ::FileExchange::UploadResponse* response, ::grpc::experimental::ClientWriteReactor< ::FileExchange::UploadRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::FileExchange::UploadRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_Upload_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::FileExchange::UploadRequest>* SimpleFileServer::Stub::AsyncUploadRaw(::grpc::ClientContext* context, ::FileExchange::UploadResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::FileExchange::UploadRequest>::Create(channel_.get(), cq, rpcmethod_Upload_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::FileExchange::UploadRequest>* SimpleFileServer::Stub::PrepareAsyncUploadRaw(::grpc::ClientContext* context, ::FileExchange::UploadResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::FileExchange::UploadRequest>::Create(channel_.get(), cq, rpcmethod_Upload_, context, response, false, nullptr);
}

::grpc::ClientReader< ::FileExchange::DownloadResponse>* SimpleFileServer::Stub::DownloadRaw(::grpc::ClientContext* context, const ::FileExchange::DownloadRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::FileExchange::DownloadResponse>::Create(channel_.get(), rpcmethod_Download_, context, request);
}

void SimpleFileServer::Stub::experimental_async::Download(::grpc::ClientContext* context, ::FileExchange::DownloadRequest* request, ::grpc::experimental::ClientReadReactor< ::FileExchange::DownloadResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::FileExchange::DownloadResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Download_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::FileExchange::DownloadResponse>* SimpleFileServer::Stub::AsyncDownloadRaw(::grpc::ClientContext* context, const ::FileExchange::DownloadRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::FileExchange::DownloadResponse>::Create(channel_.get(), cq, rpcmethod_Download_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::FileExchange::DownloadResponse>* SimpleFileServer::Stub::PrepareAsyncDownloadRaw(::grpc::ClientContext* context, const ::FileExchange::DownloadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::FileExchange::DownloadResponse>::Create(channel_.get(), cq, rpcmethod_Download_, context, request, false, nullptr);
}

SimpleFileServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SimpleFileServer_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< SimpleFileServer::Service, ::FileExchange::UploadRequest, ::FileExchange::UploadResponse>(
          [](SimpleFileServer::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::FileExchange::UploadRequest>* reader,
             ::FileExchange::UploadResponse* resp) {
               return service->Upload(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SimpleFileServer_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< SimpleFileServer::Service, ::FileExchange::DownloadRequest, ::FileExchange::DownloadResponse>(
          [](SimpleFileServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::FileExchange::DownloadRequest* req,
             ::grpc::ServerWriter<::FileExchange::DownloadResponse>* writer) {
               return service->Download(ctx, req, writer);
             }, this)));
}

SimpleFileServer::Service::~Service() {
}

::grpc::Status SimpleFileServer::Service::Upload(::grpc::ServerContext* context, ::grpc::ServerReader< ::FileExchange::UploadRequest>* reader, ::FileExchange::UploadResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SimpleFileServer::Service::Download(::grpc::ServerContext* context, const ::FileExchange::DownloadRequest* request, ::grpc::ServerWriter< ::FileExchange::DownloadResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace FileExchange

